name: Linting
on: [ push, pull_request ]
jobs:
  black:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: run black
        uses: psf/black@22.8.0
        with:
          options: "--check --diff --line-length 180 src"
  isort:
    name: Check Import Order
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: python -m pip install --upgrade isort==5.10.1
      - name: run isort
        run: "isort --check --diff src"
